import Head from 'next/head'
import Image from 'next/image'
import Switch from '../components/Switch/index'
import styles from '../styles/Home.module.css'

export default function Home () {
  return (
    <div className={styles.container}>
      <Head>
        <title>My iot app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          My iot app
        </h1>
        <div className={styles.card}>
          <Image
            src="/lamp.svg"
            alt="lamp"
            width={100}
            height={100}
          />
          <h2>Integrated Led</h2>
          <Switch
            path = {'integratedLed'}
          />
        </div>
      </main>
    </div>
  )
}
